[project]
name = 'subscriptify-on-stacks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.mock-traits]
path = 'contracts/mock-traits.clar'
clarity_version = 3
epoch = 3.1

[contracts.maths-time]
path = 'contracts/maths-time.clar'
clarity_version = 3
epoch = 3.1

[contracts.token-payment]
path = 'contracts/token-payment.clar'
clarity_version = 3
epoch = 3.1

[contracts.admin]
path = 'contracts/admin.clar'
clarity_version = 3
epoch = 3.1

[contracts.plan-manager]
path = 'contracts/plan-manager.clar'
clarity_version = 3
epoch = 3.1

[contracts.pass-nft]
path = 'contracts/pass-nft.clar'
clarity_version = 3
epoch = 3.1

[contracts.subscription-manager]
path = 'contracts/subscription-manager.clar'
clarity_version = 3
epoch = 3.1

[contracts.access-control]
path = 'contracts/access-control.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
